-- ============================================================
--  Jornada reflections: store user reflections from "personal" step
-- ============================================================

create table if not exists public.jornada_reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reflection text not null,
  created_at timestamptz not null default now()
);

alter table public.jornada_reflections enable row level security;

-- Anyone authenticated can view all reflections (public feed)
drop policy if exists "Users can view all jornada reflections" on jornada_reflections;
create policy "Users can view all jornada reflections"
  on jornada_reflections for select
  to authenticated
  using (true);

-- Users can insert their own reflections
drop policy if exists "Users can insert own jornada reflections" on jornada_reflections;
create policy "Users can insert own jornada reflections"
  on jornada_reflections for insert
  to authenticated
  with check (user_id = auth.uid());

-- RPC to save a jornada reflection
create or replace function public.save_jornada_reflection(p_reflection text)
returns void
language plpgsql
security definer
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'No autorizado para realizar esta acción';
  end if;

  if p_reflection is null or trim(p_reflection) = '' then
    return;
  end if;

  insert into jornada_reflections(user_id, reflection, created_at)
  values (v_user_id, trim(p_reflection), now());
end;
$$;

grant execute on function public.save_jornada_reflection(text) to authenticated;